version: '3'

# service description
services:

  # portainer server
  portainer-server:
    image: portainer/portainer-ce:latest
    container_name: portainer-server
    hostname: portainer-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 9000:9000
    networks:
      - traefik-net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      # enbale watchtower updates
      - "com.centurylinklabs.watchtower.enable=true"
      # enable traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      # https endpoint
      - "traefik.http.routers.portainer-web-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-web-secure.rule=Host(`${PORTAINER_CONT_URL}`)"
      - "traefik.http.routers.portainer-web-secure.tls=true"
      - "traefik.http.routers.portainer-web-secure.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.portainer-web-secure.service=portainer-service"
      # services
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"

# networks to use
networks:

  # traefik reverse proxy network
  traefik-net:
    external: true
